import React, { useState, useEffect } from "react";
import {
  View,
  Text,
  StyleSheet,
  Pressable,
  ScrollView,
  ActivityIndicator,
  Alert,
  Share,
  Linking,
  Clipboard,
} from "react-native";
import { useRouter, useLocalSearchParams } from "expo-router";
import * as Sharing from "expo-sharing";
import AsyncStorage from "@react-native-async-storage/async-storage";

const API_BASE = "https://elemetric-ai-production.up.railway.app";
const JOB_KEY = "elemetric_current_job";
const AI_RESULT_KEY = "elemetric_ai_result_decoded";

type ShareClientParams = {
  pdfUri?: string;
  jobName?: string;
  jobAddr?: string;
  confidence?: string;
};

export default function ShareClient() {
  const router = useRouter();
  const params = useLocalSearchParams<ShareClientParams>();

  const [loading, setLoading] = useState(false);
  const [summary, setSummary] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  // Pull job context from params or AsyncStorage
  const [jobName, setJobName] = useState(params.jobName ?? "");
  const [jobAddr, setJobAddr] = useState(params.jobAddr ?? "");
  const [confidence, setConfidence] = useState(
    params.confidence ? parseInt(params.confidence, 10) : 0
  );
  const pdfUri = params.pdfUri ?? null;

  useEffect(() => {
    if (jobName && jobAddr) return;
    (async () => {
      try {
        const raw = await AsyncStorage.getItem(JOB_KEY);
        if (raw) {
          const job = JSON.parse(raw);
          if (!jobName) setJobName(job.jobName ?? job.job_name ?? "");
          if (!jobAddr) setJobAddr(job.jobAddr ?? job.job_addr ?? "");
        }
      } catch {}
    })();
  }, []);

  const fetchSummary = async () => {
    setLoading(true);
    setSummary(null);
    try {
      const res = await fetch(`${API_BASE}/compliance-summary`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          job_name: jobName,
          job_addr: jobAddr,
          confidence,
        }),
      });
      if (res.ok) {
        const data = await res.json();
        const text: string =
          data.summary ?? data.message ?? buildFallback();
        setSummary(text);
      } else {
        setSummary(buildFallback());
      }
    } catch {
      setSummary(buildFallback());
    } finally {
      setLoading(false);
    }
  };

  const buildFallback = () =>
    `Compliance Summary — ${jobName}\n\n` +
    `Property: ${jobAddr}\n` +
    `Compliance Score: ${confidence}%\n\n` +
    `This property has had recent compliance work completed and documented through Elemetric. ` +
    `The AI-assisted compliance analysis returned a score of ${confidence}%. ` +
    `A full tamper-evident PDF report is available on request.\n\n` +
    `Generated by Elemetric — elemetric.com.au`;

  const handleSharePDF = async () => {
    if (!pdfUri) {
      Alert.alert("No PDF", "Generate a PDF report first from the AI Overview screen.");
      return;
    }
    try {
      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        await Sharing.shareAsync(pdfUri, {
          mimeType: "application/pdf",
          dialogTitle: "Share Compliance Report PDF",
          UTI: "com.adobe.pdf",
        });
      } else {
        await Share.share({ title: "Compliance Report", url: pdfUri });
      }
    } catch (e: any) {
      Alert.alert("Share Error", e?.message ?? "Could not share PDF.");
    }
  };

  const handleShareSummary = async () => {
    if (!summary) return;
    try {
      await Share.share({ message: summary, title: "Compliance Summary" });
    } catch {}
  };

  const handleWhatsApp = async () => {
    if (!summary) return;
    const encoded = encodeURIComponent(summary);
    const url = `whatsapp://send?text=${encoded}`;
    try {
      const can = await Linking.canOpenURL(url);
      if (can) {
        await Linking.openURL(url);
      } else {
        await Share.share({ message: summary });
      }
    } catch {
      await Share.share({ message: summary });
    }
  };

  const handleSMS = async () => {
    if (!summary) return;
    const encoded = encodeURIComponent(summary);
    await Linking.openURL(`sms:?body=${encoded}`).catch(() =>
      Share.share({ message: summary })
    );
  };

  const handleCopy = async () => {
    if (!summary) return;
    Clipboard.setString(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <View style={styles.screen}>
      <View style={styles.header}>
        <Pressable
          onPress={() => router.back()}
          style={styles.backBtn}
          accessibilityRole="button"
          accessibilityLabel="Go back"
        >
          <Text style={styles.backText}>← Back</Text>
        </Pressable>
        <Text style={styles.brand}>ELEMETRIC</Text>
        <Text style={styles.title}>Share with Client</Text>
        <Text style={styles.subtitle}>
          {jobName ? jobName : "Send your compliance report"}
        </Text>
      </View>

      <ScrollView
        contentContainerStyle={styles.body}
        showsVerticalScrollIndicator={false}
      >
        {/* ── Option 1: Share PDF ── */}
        <View style={styles.optionCard}>
          <View style={styles.optionHeader}>
            <Text style={styles.optionIcon}>📄</Text>
            <View style={styles.optionHeaderText}>
              <Text style={styles.optionTitle}>Share PDF Report</Text>
              <Text style={styles.optionSub}>
                Full tamper-evident compliance report
              </Text>
            </View>
          </View>
          <Text style={styles.optionDesc}>
            Opens the native share sheet so you can send the PDF via email, AirDrop,
            or any app. Ideal for building surveyors and formal handovers.
          </Text>
          <Pressable
            style={[styles.actionBtn, !pdfUri && styles.actionBtnDisabled]}
            onPress={handleSharePDF}
            disabled={!pdfUri}
            accessibilityRole="button"
            accessibilityLabel="Share PDF report"
            accessibilityHint="Opens system share sheet with PDF attached"
          >
            <Text style={styles.actionBtnText}>
              {pdfUri ? "Share PDF →" : "Generate PDF first in AI Overview"}
            </Text>
          </Pressable>
        </View>

        {/* ── Option 2: Compliance Summary ── */}
        <View style={styles.optionCard}>
          <View style={styles.optionHeader}>
            <Text style={styles.optionIcon}>💬</Text>
            <View style={styles.optionHeaderText}>
              <Text style={styles.optionTitle}>Share Compliance Summary</Text>
              <Text style={styles.optionSub}>Plain English — ideal for property owners</Text>
            </View>
          </View>
          <Text style={styles.optionDesc}>
            Our AI writes a plain English paragraph suitable for sending to your client
            or building surveyor — no technical jargon.
          </Text>

          {!summary && !loading && (
            <Pressable
              style={styles.actionBtn}
              onPress={fetchSummary}
              accessibilityRole="button"
              accessibilityLabel="Generate compliance summary"
            >
              <Text style={styles.actionBtnText}>Generate Summary →</Text>
            </Pressable>
          )}

          {loading && (
            <View style={styles.loadingRow}>
              <ActivityIndicator color="#f97316" size="small" />
              <Text style={styles.loadingText}>Writing summary…</Text>
            </View>
          )}

          {summary && !loading && (
            <>
              {/* Preview card */}
              <View style={styles.summaryCard}>
                <Text style={styles.summaryLabel}>SUMMARY PREVIEW</Text>
                <Text style={styles.summaryText}>{summary}</Text>
              </View>

              {/* Action buttons */}
              <View style={styles.shareRow}>
                <Pressable
                  style={styles.shareBtn}
                  onPress={handleCopy}
                  accessibilityRole="button"
                  accessibilityLabel={copied ? "Copied!" : "Copy text to clipboard"}
                >
                  <Text style={styles.shareBtnText}>
                    {copied ? "✓ Copied!" : "Copy Text"}
                  </Text>
                </Pressable>

                <Pressable
                  style={styles.shareBtn}
                  onPress={handleShareSummary}
                  accessibilityRole="button"
                  accessibilityLabel="Share via system share sheet"
                >
                  <Text style={styles.shareBtnText}>Share →</Text>
                </Pressable>
              </View>

              <View style={styles.shareRow}>
                <Pressable
                  style={[styles.shareBtn, styles.shareBtnWhatsApp]}
                  onPress={handleWhatsApp}
                  accessibilityRole="button"
                  accessibilityLabel="Share via WhatsApp"
                >
                  <Text style={styles.shareBtnText}>WhatsApp</Text>
                </Pressable>

                <Pressable
                  style={[styles.shareBtn, styles.shareBtnSMS]}
                  onPress={handleSMS}
                  accessibilityRole="button"
                  accessibilityLabel="Share via SMS"
                >
                  <Text style={styles.shareBtnText}>SMS</Text>
                </Pressable>
              </View>

              <Pressable
                style={styles.regenerateBtn}
                onPress={fetchSummary}
                accessibilityRole="button"
                accessibilityLabel="Regenerate summary"
              >
                <Text style={styles.regenerateBtnText}>↺ Regenerate</Text>
              </Pressable>
            </>
          )}
        </View>

        {/* Disclaimer */}
        <View style={styles.disclaimer}>
          <Text style={styles.disclaimerText}>
            Compliance summaries are AI-generated. The PDF report is the authoritative document for regulatory purposes. Elemetric reports reference AS/NZS 3500 series standards as enforced by the Building and Plumbing Commission of Victoria.
          </Text>
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#07152b" },
  header: { paddingTop: 52, paddingHorizontal: 20, paddingBottom: 12 },
  backBtn: { marginBottom: 10 },
  backText: { color: "#f97316", fontWeight: "700", fontSize: 15 },
  brand: { color: "#f97316", fontSize: 18, fontWeight: "900", letterSpacing: 2 },
  title: { marginTop: 8, color: "white", fontSize: 22, fontWeight: "900" },
  subtitle: { marginTop: 4, color: "rgba(255,255,255,0.55)", fontSize: 13 },
  body: { padding: 20, gap: 16, paddingBottom: 60 },

  optionCard: {
    backgroundColor: "#0f2035",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.07)",
    padding: 16,
    gap: 12,
  },
  optionHeader: { flexDirection: "row", alignItems: "center", gap: 12 },
  optionIcon: { fontSize: 28 },
  optionHeaderText: { flex: 1, gap: 2 },
  optionTitle: { color: "white", fontWeight: "900", fontSize: 16 },
  optionSub: { color: "rgba(255,255,255,0.45)", fontSize: 12 },
  optionDesc: { color: "rgba(255,255,255,0.60)", fontSize: 13, lineHeight: 20 },

  actionBtn: {
    backgroundColor: "#f97316",
    borderRadius: 14,
    height: 52,
    alignItems: "center",
    justifyContent: "center",
  },
  actionBtnDisabled: { backgroundColor: "rgba(249,115,22,0.30)" },
  actionBtnText: { color: "#07152b", fontWeight: "900", fontSize: 15 },

  loadingRow: { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 8 },
  loadingText: { color: "rgba(255,255,255,0.55)", fontSize: 14 },

  summaryCard: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(249,115,22,0.20)",
    padding: 14,
    gap: 8,
  },
  summaryLabel: {
    color: "#f97316",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  summaryText: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 14,
    lineHeight: 22,
  },

  shareRow: { flexDirection: "row", gap: 10 },
  shareBtn: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  shareBtnWhatsApp: {
    backgroundColor: "rgba(37,211,102,0.12)",
    borderColor: "rgba(37,211,102,0.30)",
  },
  shareBtnSMS: {
    backgroundColor: "rgba(59,130,246,0.12)",
    borderColor: "rgba(59,130,246,0.30)",
  },
  shareBtnText: { color: "white", fontWeight: "700", fontSize: 14 },

  regenerateBtn: { alignItems: "center", paddingVertical: 6 },
  regenerateBtnText: { color: "rgba(255,255,255,0.40)", fontWeight: "700", fontSize: 13 },

  disclaimer: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    backgroundColor: "#0f2035",
    padding: 14,
  },
  disclaimerText: {
    color: "rgba(255,255,255,0.30)",
    fontSize: 11,
    lineHeight: 17,
  },
});
